# Generated by Django 4.2.30 on 2026-06-25 03:47

from django.db import migrations
from django.contrib.postgres.indexes import GinIndex


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_initial"),
    ]

    operations = [
        # Configure GIN index on search_vector to accelerate full-text search queries
        migrations.AddIndex(
            model_name='page',
            index=GinIndex(fields=['search_vector'], name='notes_page_search_vec_gin'),
        ),
    ]
