# Generated by Django 4.2.30 on 2026-06-25 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_fts_setup"),
    ]

    operations = [
        # Create custom PL/pgSQL function to update search_vector with weights (Title = A, Content = B)
        migrations.RunSQL(
            sql="""
            CREATE OR REPLACE FUNCTION notes_page_search_vector_update_fn()
            RETURNS trigger AS $$
            BEGIN
                NEW.search_vector :=
                    setweight(to_tsvector('pg_catalog.english', COALESCE(NEW.title, '')), 'A') ||
                    setweight(to_tsvector('pg_catalog.english', COALESCE(NEW.content, '')), 'B');
                RETURN NEW;
            END
            $$ LANGUAGE plpgsql;

            CREATE TRIGGER notes_page_search_vector_update
            BEFORE INSERT OR UPDATE ON notes_page
            FOR EACH ROW
            EXECUTE FUNCTION notes_page_search_vector_update_fn();
            """,
            reverse_sql="""
            DROP TRIGGER IF EXISTS notes_page_search_vector_update ON notes_page;
            DROP FUNCTION IF EXISTS notes_page_search_vector_update_fn();
            """
        )
    ]
